# Travis's execution file
---
language: python

addons:
    apt_packages:
        - build-essential
        - git
        - curl

cache:
    directories:
        - $HOME/download/
        - $HOME/miniconda3/

python:
    # We don't actually use the Travis Python, but this keeps it organized.
    # - "2.7"
    - "3.5"
    # - "3.6"


install:
    - sudo apt-get update
    # We do this conditionally because it saves us some downloading if the
    # version is the same.
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
            wget
            https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh
            -O miniconda.sh;
      else
        wget
        https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
        -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # Useful for debugging any issues with conda
    - conda info -a
    # Use bioconda and conda-forge
    - conda config --add channels defaults
    - conda config --add channels conda-forge
    - conda config --add channels bioconda
    - conda install --yes snakemake=5.0.0
    - conda clean --all --yes

script:
    - export PATH="/home/travis/miniconda3/bin:$PATH"
    - echo $PATH
    - ./pre-commit
