#!/usr/bin/env bash

set -euo pipefail

# pre-commit hooks:
# check that the pipeline works,
# check linters:
#   python conde: pylint
#   shell: shellcheck
#   yaml: yamllint
#   r: lintr


# Pipeline
do_clean() {
    snakemake --version
    snakemake clean
}

do_pipeline_dry_run() {
    snakemake --version
    snakemake --dryrun --printshellcmds -j
}

do_pipeline() {
    snakemake --version
    snakemake --use-conda -j
}


do_pylint_snakefiles() {
    # pylint the main Snakefile and the *.py files in src/snakefiles/

    pylint --version

    pylint \
        --disable=syntax-error \
        Snakefile src/snakefiles/*.py

}

do_pylint_python() {
    # Pylint python scripts over the src/ folder
    pylint --version

    find \
        src \
        -name "*.py" \
        -type f \
        -maxdepth 1 \
        -print0 \
    | xargs -0 pylint

}

do_shellcheck(){
    # Perform shellcheck over the *.sh files in src/

    shellcheck --version

    # Check all *.sh files
    find \
        src/ \
        -maxdepth 1 \
        -type f \
        -name "*.sh" \
    | xargs shellcheck
}

do_yamllint(){
    # yamllint over yaml files in . and src/snakefiles/
    yamllint --version

    find \
        . src/snakefiles/ \
        -maxdepth 1 \
        -type f \
        -name "*.yml" -o -name "*.yaml" \
    | xargs yamllint --strict
}


# Error
fail () {
    echo "$0: [FAILED]"
    exit 1
}


# Check tree
if git rev-parse --verify HEAD >/dev/null 2>&1
then
        against=HEAD
else
        # Initial commit: diff against an empty tree object
        against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Run everything
echo "Cleaning results"
do_clean || fail clean
echo

echo "Checking the pipeline"
do_pipeline_dry_run || fail pipeline_dry_run
echo

echo "Linting Snakefiles"
do_pylint_snakefiles || fail pylint_snakefiles
echo

echo "Linting Python scripts"
do_pylint_python || fail pylint
echo

echo "Linting Shell scripts"
do_shellcheck || fail shellcheck
echo

echo "Linting YAML files"
do_yamllint || fail yamllint
echo

echo "Running the pipeline"
do_pipeline || fail Snakemake
echo

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
